# Dependabot Configuration
#
# References:
#
# - https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
registries:
  gpr:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: ${{ github.repository_owner }}
    password: ${{ secrets.PAT_GPR_ADMIN }}
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    labels:
      - type:ci
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build
      include: scope
    labels:
      - type:build
    registries:
      - gpr
