# Automate Pull Request Reviews
#
# References:
#
# - https://github.com/actions/checkout
# - https://github.com/flex-development/flautoreview

---
name: automate-pr-reviews
on:
  pull_request:
    types: [review_requested]
jobs:
  autoreview:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout branch
        uses: actions/checkout@v3
      - id: review
        name: Automate reviews
        uses: flex-development/flautoreview@v1.0.1
        with:
          body: lgtm ğŸ‘ğŸ¾
          reviewers: flexdevelopment
          senders: unicornware
          token: ${{ secrets.PAT_REPO_ADMIN }}
